[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'chromium']

[phases.install]
cmds = [
    'python -m venv /opt/venv',
    '. /opt/venv/bin/activate && pip install --upgrade pip',
    '. /opt/venv/bin/activate && pip install -r requirements.txt',
    '. /opt/venv/bin/activate && playwright install --with-deps chromium'
]

[variables]
PATH = '/opt/venv/bin:$PATH'

[start]
cmd = "/opt/venv/bin/gunicorn --bind 0.0.0.0:$PORT app:app"
