[phases.setup]
nixPkgs = ["python310", "pip", "nodejs"]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "python -m pip install -r requirements.txt",
    "python -m playwright install --with-deps chromium"
]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT app:app"
