[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'chromium']

[phases.install]
cmds = [
    'pip install -r requirements.txt',
    'playwright install --with-deps chromium'
]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT app:app"
