[phases.setup]
nixPkgs = ['nodejs', 'python310']

[phases.install]
cmds = [
    'python -m pip install --upgrade pip',
    'python -m pip install -r requirements.txt'
]

[phases.build]
cmds = ['./build.sh']

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT app:app"
